#pragma once

#include "vm.h"
#include "memory.h"
#include "operands.h"
#include <stdio.h>

#define VM_DEFINE_OPERATION_H_INDIRECT(mnemonic) void vm_op_##mnemonic(vm_state* vm);
// Defines an operation that must be implemented
#define VM_DEFINE_OPERATION_H(mnemonic,x) VM_DEFINE_OPERATION_H_INDIRECT(mnemonic)

extern vm_ophandler_t vm_OpHandlers[0xFF + 1];

VM_DEFINE_OPERATION_H(PUSH, 1)
VM_DEFINE_OPERATION_H(POP, 2)
VM_DEFINE_OPERATION_H(MOV, 3)
VM_DEFINE_OPERATION_H(JMP, 4)
VM_DEFINE_OPERATION_H(XCHG, 5)
VM_DEFINE_OPERATION_H(XCHG, 6)
VM_DEFINE_OPERATION_H(ADD, 7)
VM_DEFINE_OPERATION_H(SUB, 8)
VM_DEFINE_OPERATION_H(MUL, 9)
VM_DEFINE_OPERATION_H(DIV, 16)
VM_DEFINE_OPERATION_H(IMUL, 17)
VM_DEFINE_OPERATION_H(IDIV, 18)
VM_DEFINE_OPERATION_H(IN, 19)
VM_DEFINE_OPERATION_H(OUT, 20)
VM_DEFINE_OPERATION_H(CALL, 21)
VM_DEFINE_OPERATION_H(RET, 22)
VM_DEFINE_OPERATION_H(JE, 23)
VM_DEFINE_OPERATION_H(JNE, 24)
VM_DEFINE_OPERATION_H(JZ, 25)
VM_DEFINE_OPERATION_H(JG, 32)
VM_DEFINE_OPERATION_H(JGE, 33)
VM_DEFINE_OPERATION_H(JL, 34)
VM_DEFINE_OPERATION_H(JLE, 35)
VM_DEFINE_OPERATION_H(CMP, 36)
VM_DEFINE_OPERATION_H(IRET, 37)
VM_DEFINE_OPERATION_H(DBGHALT, 38)
VM_DEFINE_OPERATION_H(SETCHAR, 39)
VM_DEFINE_OPERATION_H(GETCHAR, 40)
VM_DEFINE_OPERATION_H(MOD, 41)
VM_DEFINE_OPERATION_H(TIMER, 48)
VM_DEFINE_OPERATION_H(AND, 49)
VM_DEFINE_OPERATION_H(XOR, 50)
VM_DEFINE_OPERATION_H(OR, 51)
VM_DEFINE_OPERATION_H(NOT, 52)
VM_DEFINE_OPERATION_H(TEST, 53)